/***** DO NOT EDIT THIS FILE *****/
// Testapp_1.js generated by MonkeyTalk

load("libs/MonkeyTalkAPI.js");


var Testapp_1 = {};

/*** script -- Settings ***/
Testapp_1.Settings = function(app) {
	MT.Script.call(this, app, "Settings.mt");
};

Testapp_1.Settings.prototype = new MT.Script;

Testapp_1.Settings.prototype.call = function() {
	//run: Settings.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.settings = function() {
	return new Testapp_1.Settings(this);
};

